#include "Common.h"
#include "DalvikHeader.h"


struct FuncMap
{
	Method* method;
	void* jniFunc;
};

#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO, "CydiaSubstrate", __VA_ARGS__)
#define NAKED __attribute__ ((naked))


typedef void* (*JavaMethodCallback)(void** stack, FuncMap* data);

static unsigned elfhash(const char *_name)
{
    const unsigned char *name = (const unsigned char *) _name;
    unsigned h = 0, g;

    while(*name)
    {
        h = (h << 4) + *name++;
        g = h & 0xf0000000;
        h ^= g;
        h ^= g >> 24;
    }
    return h;
}

JNIEXPORT void* JNICALL MSFindSymbol(MSImageRef image, const char *name)
{
	soinfo* si = (soinfo*)image;
	unsigned int hash = elfhash(name);
	Elf32_Sym* s;
	Elf32_Sym* symtab = si->symtab;
	const char* strtab = (const char*)si->strtab;
	unsigned int n = hash % si->nbucket;
	for(n = si->bucket[hash % si->nbucket];n != 0;n = si->chain[n])
	{
		s = symtab + n;
		if(s->st_shndx && !strcmp(name, strtab + s->st_name))
			return (void*)(si->base + s->st_value);
	}
	return 0;
}

JNIEXPORT MSImageRef JNICALL MSGetImageByName(const char *file)
{
	static void* dllibdl = dlopen("libdl/so", RTLD_LAZY | RTLD_GLOBAL);
	if(!file)
		return 0;
	char* p = strrchr(file, '/');
	if(p)
		file = p + 1;
	soinfo* iter = (soinfo*)dllibdl;
	while(iter)
	{
		if(!strcmp((const char*)iter->name, file))
			return (MSImageRef)iter;
		iter = iter->next;
	}
	return 0;
}

JNIEXPORT void* JNICALL MSCloseFunction(void* callback,void* data)
{
	void* base;
	unsigned int buf[]=
	{
		/*
		 	void* func(JNIEnv* env, jobject jobj,...)
		 	{
		 		callback(__ARGS__, data);//第一个参数为func的参数栈，包含所有参数，第二个参数为data
		 	}
			STMFD           SP!, {R0-R3}
			SUB             SP, SP, #4
			STMFD           SP!, {LR}
			ADD             R0, SP, #0x18+varg_r0
			LDR             R1, =mapdata
			LDR             R12, =callback
			BLX             R12 ; callback
			LDMFD           SP!, {LR}
			ADD             SP, SP, #0x14
			BX              LR
		*/
		0xE92D000F,
		0xE24DD004,
		0xE92D4000,
		0xE28D0008,
		0xE59F1010,
		0xE59FC010,
		0xE12FFF3C,
		0xE8BD4000,
		0xE28DD014,
		0xE12FFF1E,
		(unsigned int)mapdata,
		(unsigned int)callback,
	};
	dosafe(base, mmap(0, sizeof(buf), PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0));
	if(base != MAP_FAILED)
	{
		memcpy(base, buf, sizeof(buf));
		int status;
		dosafe(status, mprotect(base, sizeof(buf), PROT_READ | PROT_EXEC));
		if(status == -1)
		{
			dosafe(status, munmap(base, sizeof(buf)));
			return 0;
		}
		return base;
	}
}

JNIEXPORT bool MSDebug = false;

struct ModRan//存储修改的内存块
{
	unsigned int begin;
	unsigned int length;
};

//修改内存块具有读写执行权限
ModRan* ModForRWEAlloc(void* base, int length)
{
	if(!base || !length)
		return 0;
	unsigned int pagesize = getpagesize();
	unsigned int beginaddr,endaddr;
	beginaddr = pagesize * ((unsigned int)base / pagesize);
	endaddr = pagesize + pagesize * (((unsigned int)base + length - 1) / pagesize);
	int status;
	dosafe(status, mprotect((void*)beginaddr, endaddr - beginaddr, PROT_READ | PROT_WRITE | PROT_EXEC));
	if(status != -1)
	{
		ModRan* mem = new ModRan;
		mem->begin = beginaddr;
		mem->length = endaddr - beginaddr;
		return mem;
	}
	return 0;
}

void NAKED cacheFlush(unsigned int, unsigned int)
{
	__asm__(
		"STMFD   SP!, {R7}\n"
		"LDR     R7, =#983042\n"
		"MOV     R2, #0\n"
		"SVC     0\n"
		"LDMFD   SP!, {R7}\n"
		"BX      LR"
	);
}

void ModForRWEFree(ModRan* mod)
{
	if(!mod)
		return;
	int status;
	dosafe(status, mprotect((void*)mod->begin, mod->length, PROT_READ | PROT_WRITE | PROT_EXEC));
	cacheFlush(mod->begin, mod->begin + mod->length);
	delete mod;
}

extern "C" void NAKED HookFunctionThumb(void *symbol, void *replace, void **result)
{
	asm(
			"fd		= -0xB4                                \n"
			"offset		= -0xB0                            \n"
			"dest		= -0xAC                            \n"
			"var_A8		= -0xA8                            \n"
			"var_A4		= -0xA4                            \n"
			"var_A0		= -0xA0                            \n"
			"var_9C		= -0x9C                            \n"
			"var_98		= -0x98                            \n"
			"var_94		= -0x94                            \n"
			"var_90		= -0x90                            \n"
			"var_8C		= -0x8C                            \n"
			"var_88		= -0x88                            \n"
			"var_84		= -0x84                            \n"
			"var_80		= -0x80                            \n"
			"var_7C		= -0x7C                            \n"
			"var_78		= -0x78                            \n"
			"var_74		= -0x74                            \n"
			"var_70		= -0x70                            \n"
			"var_6C		= -0x6C                            \n"
			"var_68		= -0x68                            \n"
			"var_64		= -0x64                            \n"
			"n		= -0x5C                                \n"
			"var_58		= -0x58                            \n"
			"len		= -0x54                            \n"
			"var_50		= -0x50                            \n"
			"var_4C		= -0x4C                            \n"
			"var_48		= -0x48                            \n"
			"var_44		= -0x44                            \n"
			"var_40		= -0x40                            \n"
			"var_3C		= -0x3C                            \n"
			"var_38		= -0x38                            \n"
			"s		= -0x34                                \n"
			"		STMFD	SP!, {R4-R11,LR}               \n"
			"		SUBS	R5, R0,	#0                     \n"
			"		ADD	R11, SP, #0x20                     \n"
			"		SUB	SP, SP,	#0x94                      \n"
			"		STR	R1, [R11,#var_80]                  \n"
			"		STR	R2, [R11,#var_74]                  \n"
			"		STR	SP, [R11,#var_7C]                  \n"
			"		BEQ	loc_10F4                           \n"
			"		TST	R5, #2                             \n"
			"		MOVEQ	R7, #0                         \n"
			"		MOVNE	R7, #1                         \n"
			"		MOV	R9, R7,LSL#1                       \n"
			"		ADD	R10, R5, R9                        \n"
			"		ADD	R12, R10, #0xC                     \n"
			"		RSB	R3, R5,	R12                        \n"
			"		BIC	R3, R3,	#1                         \n"
			"		CMP	R7, #0                             \n"
			"		STR	R7, [R11,#var_6C]                  \n"
			"		STR	R9, [R11,#var_70]                  \n"
			"		STR	R10, [R11,#var_64]                 \n"
			"		STR	R12, [R11,#var_78]                 \n"
			"		STR	R3, [R11,#var_68]                  \n"
			"		BNE	loc_1420                           \n"
			"		LDR	R7, [R11,#var_70]                  \n"
			"		MOV	R3, %[VAL_4778]                    \n"
			"		LDRH	R2, [R5,R7]                    \n"
			"		CMP	R2, R3                             \n"
			"		BEQ	loc_18BC                           \n"
			"loc_D68:				                       \n"
			"		LDR	R10, [R11,#var_68]                 \n"
			"		CMP	R10, #0                            \n"
			"		MOVEQ	R3, R10                        \n"
			"		MOVEQ	R4, R3                         \n"
			"		STREQ	R10, [R11,#n]                  \n"
			"		BEQ	loc_DD4                            \n"
			"		MOV	R3, #0                             \n"
			"		LDR	R12, [R11,#var_68]                 \n"
			"		B	loc_D98                            \n"
			"loc_D8C:				                       \n"
			"		ADD	R3, R3,	R2                         \n"
			"		CMP	R12, R3                            \n"
			"		BLS	loc_DC0                            \n"
			"loc_D98:				                       \n"
			"					                           \n"
			"		LDRH	R1, [R5,R3]                    \n"
			"		MOV	R2, #2                             \n"
			"		AND	R0, R1,	#0xE000                    \n"
			"		CMP	R0, #0xE000                        \n"
			"		BNE	loc_D8C                            \n"
			"		TST	R1, #0x1800                        \n"
			"		MOVNE	R2, #4                         \n"
			"		ADD	R3, R3,	R2                         \n"
			"		CMP	R12, R3                            \n"
			"		BHI	loc_D98                            \n"
			"loc_DC0:				                       \n"
			"		ADD	R3, R3,	#1                         \n"
			"		BIC	R3, R3,	#1                         \n"
			"		MOV	R4, R3,LSR#1                       \n"
			"		STR	R3, [R11,#n]                       \n"
			"		MOV	R3, R4,LSL#1                       \n"
			"loc_DD4:				                       \n"
			"		ADD	R3, R3,	#0xE                       \n"
			"		BIC	R3, R3,	#7                         \n"
			"		SUB	SP, SP,	R3                         \n"
			"		ADD	R6, SP,	#0xB4+dest                 \n"
			"		MOV	R0, R6		                       \n"
			"		MOV	R1, R5		                       \n"
			"		LDR	R2, [R11,#n]	                   \n"
			"		BL	memcpy                             \n"
			"loc_E0C:				                       \n"
			"		LDR	R12, [R11,#var_74]                 \n"
			"		CMP	R12, #0                            \n"
			"		BEQ	loc_1054                           \n"
			"		CMP	R4, #0                             \n"
			"		LDREQ	R12, [R11,#n]                  \n"
			"		BEQ	loc_EB4                            \n"
			"		LDR	R12, [R11,#n]                      \n"
			"		MOV	R7, #0xF800                        \n"
			"		MOV	R8, #0x4400                        \n"
			"		MOV	R3, #0                             \n"
			"		ADD	R7, R7,	#0x5F                      \n"
			"		ADD	R8, R8,	#0x78                      \n"
			"loc_E3C:				                       \n"
			"					                           \n"
			"		MOV	R0, R3,LSL#1                       \n"
			"		LDRH	R2, [R6,R0]                    \n"
			"		AND	R1, R2,	#0xF800                    \n"
			"		CMP	R1, #0x4800                        \n"
			"		ADDEQ	R12, R12, #6                   \n"
			"		BEQ	loc_EA8                            \n"
			"		AND	LR, R2,	#0xF000                    \n"
			"		CMP	LR, #0xD000                        \n"
			"		BEQ	loc_121C                           \n"
			"loc_E60:				                       \n"
			"		CMP	R1, #0xE000                        \n"
			"		BEQ	loc_1228                           \n"
			"		CMP	R1, #0xF000                        \n"
			"		BEQ	loc_13D0                           \n"
			"loc_E70:				                       \n"
			"		AND	R1, R2,	#0xF500                    \n"
			"		CMP	R1, #0xB100                        \n"
			"		BEQ	loc_1AD8                           \n"
			"		BIC	R1, R2,	#0x80                      \n"
			"		CMP	R1, R7                             \n"
			"		ADDEQ	R12, R12, #8                   \n"
			"		ADDEQ	R3, R3,	#1                     \n"
			"		BEQ	loc_EA8                            \n"
			"		BIC	R1, R2,	#0x87                      \n"
			"		CMP	R1, R8                             \n"
			"		BEQ	loc_1228                           \n"
			"		AND	R1, R2,	#0xE000                    \n"
			"		CMP	R1, #0xE000                        \n"
			"		BEQ	loc_1ACC                           \n"
			"loc_EA8:				                       \n"
			"					                           \n"
			"		ADD	R3, R3,	#1                         \n"
			"		CMP	R3, R4                             \n"
			"		BNE	loc_E3C                            \n"
			"loc_EB4:				                       \n"
			"					                           \n"
			"		TST	R12, #2                            \n"
			"		MOVNE	R3, #0xE                       \n"
			"		MOVEQ	R3, #0xC                       \n"
			"		MOVEQ	R7, #0                         \n"
			"		MOVNE	R7, #1                         \n"
			"		ADD	R3, R3,	R12                        \n"
			"		STR	R7, [R11,#var_58]                  \n"
			"		STR	R3, [R11,#len]                     \n"
			"		MOV	R10, #0xFFFFFFFF                   \n"
			"		MOV	R9, #0                             \n"
			"loc_EDC:				                       \n"
			"		MOV	R7, #0                             \n"
			"		LDR	R1, [R11,#len]	                   \n"
			"		MOV	R2, #3		                       \n"
			"		MOV	R3, #0x22	                       \n"
			"		STR	R10, [SP,#0xB4+fd]                 \n"
			"		STR	R9, [SP,#0xB4+offset]              \n"
			"		MOV	R0, R7		                       \n"
			"		BL	mmap                               \n"
			"		CMN	R0, #1                             \n"
			"		BEQ	loc_14A8                           \n"
			"		CMP	R4, #0                             \n"
			"		MOV	R8, R0                             \n"
			"		LDREQ	R3, [R11,#var_58]              \n"
			"		BEQ	loc_FDC                            \n"
			"		LDR	R10, [R11,#len]                    \n"
			"		MOV	R12, #0xBC00                       \n"
			"		MOV	LR, #0xB400                        \n"
			"		MOV	R1, R10,LSR#1                      \n"
			"		MOV	R0, #0xF400                        \n"
			"		MOV	R9, #0xF300                        \n"
			"		LDR	R3, [R11,#var_58]                  \n"
			"		ADD	R12, R12, #0x80                    \n"
			"		ADD	LR, LR,	#0x80                      \n"
			"		SUB	R0, R0,	#0x79                      \n"
			"		ADD	R9, R9,	#0x86                      \n"
			"		ADD	R2, R8,	R1,LSL#1                   \n"
			"		STR	R12, [R11,#var_38]                 \n"
			"		STR	LR, [R11,#var_3C]                  \n"
			"		STR	R0, [R11,#var_40]                  \n"
			"		STR	R9, [R11,#var_44]                  \n"
			"loc_F54:				                       \n"
			"					                           \n"
			"		MOV	R12, R7,LSL#1                      \n"
			"		LDRH	LR, [R6,R12]                   \n"
			"		AND	R0, LR,	#0xF800                    \n"
			"		CMP	R0, #0x4800                        \n"
			"		BEQ	loc_1100                           \n"
			"		AND	R10, LR, #0xF000                   \n"
			"		CMP	R10, #0xD000                       \n"
			"		BEQ	loc_1198                           \n"
			"loc_F74:				                       \n"
			"		CMP	R0, #0xE000                        \n"
			"		BEQ	loc_123C                           \n"
			"		CMP	R0, #0xF000                        \n"
			"		BEQ	loc_1274                           \n"
			"loc_F84:				                       \n"
			"		AND	R0, LR,	#0xF500                    \n"
			"		CMP	R0, #0xB100                        \n"
			"		BEQ	loc_1628                           \n"
			"		MOV	R0, #0xF800                        \n"
			"		BIC	R10, LR, #0x80                     \n"
			"		ADD	R0, R0,	#0x5F                      \n"
			"		CMP	R10, R0                            \n"
			"		BEQ	loc_17E4                           \n"
			"		MOV	R0, #0x4400                        \n"
			"		BIC	R10, LR, #0x87                     \n"
			"		ADD	R0, R0,	#0x78                      \n"
			"		CMP	R10, R0                            \n"
			"		BEQ	loc_1978                           \n"
			"		AND	R0, LR,	#0xE000                    \n"
			"		CMP	R0, #0xE000                        \n"
			"		MOV	R0, R3,LSL#1                       \n"
			"		BEQ	loc_1AFC                           \n"
			"loc_FC8:				                       \n"
			"		ADD	R7, R7,	#1                         \n"
			"		CMP	R7, R4                             \n"
			"		STRH	LR, [R8,R0]                    \n"
			"		ADD	R3, R3,	#1                         \n"
			"		BNE	loc_F54                            \n"
			"loc_FDC:				                       \n"
			"					                           \n"
			"		MOV	R0, #0x4700                        \n"
			"		MOV	R1, #0x4600                        \n"
			"		ADD	R2, R3,	#2                         \n"
			"		MOV	LR, R3,LSL#1                       \n"
			"		ADD	R0, R0,	#0x78                      \n"
			"		ADD	R3, R8,	R3,LSL#1                   \n"
			"		ADD	R1, R1,	#0xC0                      \n"
			"		STRH	R0, [R8,LR]                    \n"
			"		STRH	R1, [R3,#2]                    \n"
			"		LDR	R3, =0xE51FF004                    \n"
			"		ADD	R4, R5,	R4,LSL#1                   \n"
			"		ADD	R12, R8, R2,LSL#1                  \n"
			"		ADD	R4, R4,	#1                         \n"
			"		STR	R3, [R8,R2,LSL#1]                  \n"
			"		MOV	R0, R8		                       \n"
			"		LDR	R1, [R11,#len]	                   \n"
			"		MOV	R2, #5		                       \n"
			"		STR	R4, [R12,#4]                       \n"
			"		BL	mprotect                           \n"
			"		CMN	R0, #1                             \n"
			"		BEQ	loc_1B24                           \n"
			"		LDR	R9, [R11,#var_58]                  \n"
			"		LDR	R10, [R11,#var_74]                 \n"
			"		ADD	R2, R8,	R9,LSL#1                   \n"
			"		ADD	R2, R2,	#1                         \n"
			"		STR	R2, [R10]                          \n"
			"loc_1054:				                       \n"
			"					                           \n"
			"		MOV	R0, #0                             \n"
			"		LDR	R3, [R11,#n]                       \n"
			"		MOV	R1, R0                             \n"
			"		MOV	R2, R5                             \n"
			"		BL	ModForRWEAlloc                     \n"
			"		LDR	R12, [R11,#var_6C]                 \n"
			"		LDR	R7, [R11,#n]                       \n"
			"		LDR	R9, [R11,#var_68]                  \n"
			"		CMP	R12, #0                            \n"
			"		LDR	R10, [R11,#var_70]                 \n"
			"		MOVNE	R3, #0x4600                    \n"
			"		MOV	R1, #0x4700                        \n"
			"		ADDNE	R3, R3,	#0xC0                  \n"
			"		ADD	R1, R1,	#0x78                      \n"
			"		STRNEH	R3, [R5]                       \n"
			"		LDR	R12, [R11,#var_64]                 \n"
			"		STRH	R1, [R5,R10]                   \n"
			"		RSB	R3, R9,	R7                         \n"
			"		LDR	R1, =0xE51FF004                    \n"
			"		LDR	R7, [R11,#var_80]                  \n"
			"		MOV	R2, %[VAL_46C0]	                   \n"
			"		MOVS	R3, R3,LSR#1                   \n"
			"		STRH	R2, [R12,#2]                   \n"
			"		STR	R1, [R12,#4]                       \n"
			"		STR	R7, [R12,#8]                       \n"
			"		BEQ	loc_10D8                           \n"
			"		LDR	R12, [R11,#var_78]                 \n"
			"		MOV	R1, #0                             \n"
			"loc_10C8:				                       \n"
			"		ADD	R1, R1,	#1	                       \n"
			"		CMP	R3, R1                             \n"
			"		STRH	R2, [R12],#2                   \n"
			"		BNE	loc_10C8                           \n"
			"loc_10D8:				                       \n"
			"		CMP	R0, #0                             \n"
			"		BEQ	loc_10F4                           \n"
			"		BL	ModForRWEFree                      \n"
			"loc_10F4:				                       \n"
			"		LDR	SP, [R11,#var_7C]                  \n"
			"		SUB	SP, R11, #0x20                     \n"
			"		LDMFD	SP!, {R4-R11,PC}               \n"
			"loc_1100:				                       \n"
			"		SUB	R9, R1,	#0x80000004                \n"
			"		ANDS	R10, R3, #1                    \n"
			"		RSB	R9, R3,	R9                         \n"
			"		MOVNE	R10, #2                        \n"
			"		ADD	R9, R10, R9,LSL#1                  \n"
			"		MOV	R0, LR,LSR#8                       \n"
			"		AND	R0, R0,	#7                         \n"
			"		MOV	R9, R9,LSL#22                      \n"
			"		STR	R9, [R11,#var_84]                  \n"
			"		ORR	R9, R0,	#0x6800                    \n"
			"		STR	R9, [R11,#var_4C]                  \n"
			"		ADD	R9, R8,	R3,LSL#1                   \n"
			"		STR	R9, [R11,#var_48]                  \n"
			"		LDR	R9, [R11,#var_84]                  \n"
			"		MOV	R10, R0,LSL#8                      \n"
			"		ADD	R12, R5, R12                       \n"
			"		ORR	R10, R10, #0x4800                  \n"
			"		ORR	R10, R10, R9,LSR#24                \n"
			"		ADD	R12, R12, #4                       \n"
			"		LDR	R9, [R11,#var_4C]                  \n"
			"		BIC	R12, R12, #2                       \n"
			"		STR	R12, [R11,#var_50]                 \n"
			"		ORR	R0, R9,	R0,LSL#3                   \n"
			"		MOV	R12, R3,LSL#1                      \n"
			"		LDR	R9, [R11,#var_50]                  \n"
			"		STRH	R10, [R8,R12]                  \n"
			"		LDR	R10, [R11,#var_48]                 \n"
			"		AND	LR, LR,	#0xFF                      \n"
			"		ADD	LR, R9,	LR,LSL#2                   \n"
			"		STRH	R0, [R10,#2]                   \n"
			"		ADD	R3, R3,	#2                         \n"
			"		STR	LR, [R2,#-4]                       \n"
			"		SUB	R1, R1,	#2                         \n"
			"		SUB	R2, R2,	#4                         \n"
			"loc_1188:				                       \n"
			"					                           \n"
			"		ADD	R7, R7,	#1                         \n"
			"		CMP	R7, R4                             \n"
			"		BNE	loc_F54                            \n"
			"		B	loc_FDC                            \n"
			"loc_1198:				                       \n"
			"		AND	R10, LR, #0xE00                    \n"
			"		CMP	R10, #0xE00                        \n"
			"		BEQ	loc_F74                            \n"
			"		MOV	R0, LR,LSR#8                       \n"
			"		AND	R0, R0,	#0xF                       \n"
			"		CMP	R0, #0xE                           \n"
			"		SUBEQ	R0, R1,	#0x80000008            \n"
			"		RSBEQ	R0, R3,	R0                     \n"
			"		SUBNE	R10, R1, #0x80000008           \n"
			"		MOVEQ	R0, R0,LSL#21                  \n"
			"		RSBNE	R10, R3, R10                   \n"
			"		MOV	LR, LR,LSL#24                      \n"
			"		ORR	LR, LR,	#0x800000                  \n"
			"		ANDNE	R10, R10, #0xFF                \n"
			"		MOVEQ	R0, R0,LSR#21                  \n"
			"		ORRNE	R0, R10, R0,LSL#8              \n"
			"		MOV	LR, LR,ASR#23                      \n"
			"		MOV	R9, R3,LSL#1                       \n"
			"		ORREQ	R0, R0,	#0xE000                \n"
			"		ORRNE	R0, R0,	#0xD000                \n"
			"		ADD	LR, LR,	#4                         \n"
			"		ADD	R12, R5, R12                       \n"
			"		ADD	R12, LR, R12                       \n"
			"		STRH	R0, [R8,R9]                    \n"
			"loc_11F8:				                       \n"
			"					                           \n"
			"		LDR	R0, =0xE51FF004                    \n"
			"		STR	R12, [R2,#-4]                      \n"
			"		ADD	R3, R3,	#1                         \n"
			"		STR	R0, [R2,#-8]                       \n"
			"		LDR	R0, =0x46C04778                    \n"
			"		SUB	R1, R1,	#6                         \n"
			"		STR	R0, [R2,#-0xC]                     \n"
			"		SUB	R2, R2,	#0xC                       \n"
			"		B	loc_1188                           \n"
			"loc_121C:				                       \n"
			"		AND	LR, R2,	#0xE00                     \n"
			"		CMP	LR, #0xE00                         \n"
			"		BEQ	loc_E60                            \n"
			"loc_1228:				                       \n"
			"					                           \n"
			"		ADD	R3, R3,	#1                         \n"
			"		CMP	R3, R4                             \n"
			"		ADD	R12, R12, #0xC                     \n"
			"		BNE	loc_E3C                            \n"
			"		B	loc_EB4                            \n"
			"loc_123C:				                       \n"
			"		SUB	R10, R1, #0x80000008               \n"
			"		RSB	R10, R3, R10                       \n"
			"		MOV	R10, R10,LSL#21                    \n"
			"		MOV	LR, LR,LSL#21                      \n"
			"		ORR	LR, LR,	#0x100000                  \n"
			"		MVN	R10, R10,LSR#2                     \n"
			"		MOV	LR, LR,ASR#20                      \n"
			"		ADD	LR, LR,	#4                         \n"
			"		ADD	R12, R5, R12                       \n"
			"		MOV	R0, R3,LSL#1                       \n"
			"		MVN	R10, R10,LSR#19                    \n"
			"		ADD	R12, LR, R12                       \n"
			"		STRH	R10, [R8,R0]                   \n"
			"		B	loc_11F8                           \n"
			"loc_1274:				                       \n"
			"		ADD	R0, R6,	R12                        \n"
			"		LDRH	R10, [R0,#2]                   \n"
			"		AND	R0, R10, #0xD000                   \n"
			"		CMP	R0, #0x9000                        \n"
			"		BEQ	loc_14E8                           \n"
			"		CMP	R0, #0x8000                        \n"
			"		BEQ	loc_14DC                           \n"
			"		CMP	R0, #0xD000                        \n"
			"		BEQ	loc_12AC                           \n"
			"loc_1298:				                       \n"
			"		MOV	R0, %[VAL_D001]                    \n"
			"		AND	R0, R10, R0                        \n"
			"		CMP	R0, #0xC000                        \n"
			"		BNE	loc_F84                            \n"
			"loc_12AC:				                       \n"
			"		ADD	R7, R7,	#1                         \n"
			"		MOV	R0, R7,LSL#1                       \n"
			"		LDRH	R10, [R6,R0]                   \n"
			"		STR	R7, [R11,#var_48]                  \n"
			"		MOV	R9, LR,LSL#22                      \n"
			"		MOV	R7, R10,LSL#16                     \n"
			"		MOV	R0, LR,LSR#10                      \n"
			"		MOV	LR, R7,LSL#2                       \n"
			"		STR	LR, [R11,#var_50]                  \n"
			"		MOV	LR, R7,LSL#3                       \n"
			"		STR	LR, [R11,#var_4C]                  \n"
			"		LDR	LR, [R11,#var_50]                  \n"
			"		AND	R0, R0,	#1                         \n"
			"		MOV	R9, R9,LSR#10                      \n"
			"		CMP	R0, LR,LSR#31                      \n"
			"		LDR	LR, [R11,#var_4C]                  \n"
			"		MOV	R7, R7,LSL#4                       \n"
			"		ORR	R9, R9,	R0,LSL#24                  \n"
			"		MOV	R10, R10,LSL#21                    \n"
			"		ORR	R9, R9,	LR,LSR#31                  \n"
			"		ORR	R10, R9, R10,LSR#20                \n"
			"		MOVNE	LR, #0                         \n"
			"		MOVEQ	LR, #0x800000                  \n"
			"		CMP	R0, R7,LSR#31                      \n"
			"		RSB	R0, R3,	R1                         \n"
			"		ORR	LR, R10, LR                        \n"
			"		SUB	R0, R0,	#0x80000004                \n"
			"		MOVNE	R7, #0                         \n"
			"		MOVEQ	R7, #0x400000                  \n"
			"		ADD	R12, R5, R12                       \n"
			"		ORR	R7, LR,	R7                         \n"
			"		MOV	R9, R0,LSR#1                       \n"
			"		ADD	R12, R12, #4                       \n"
			"		MOV	R7, R7,LSL#7                       \n"
			"		STR	R12, [R11,#var_94]                 \n"
			"		AND	R9, R9,	#0xFF                      \n"
			"		MOV	R12, R3,LSL#1                      \n"
			"		STR	R7, [R11,#var_4C]                  \n"
			"		STR	R12, [R11,#var_50]                 \n"
			"		ORR	R9, R9,	#0x4F00                    \n"
			"		ADD	R12, R8, R3,LSL#1                  \n"
			"		STR	R12, [R11,#var_84]                 \n"
			"		STR	R9, [R11,#var_98]                  \n"
			"		STR	R12, [R11,#var_88]                 \n"
			"		STR	R12, [R11,#var_8C]                 \n"
			"		STR	R12, [R11,#var_90]                 \n"
			"		LDR	R9, [R11,#var_94]                  \n"
			"		LDR	R12, [R11,#var_4C]                 \n"
			"		MOV	R10, %[VAL_FFFFB480]                   \n"
			"		ADD	R9, R9,	R12,ASR#7                  \n"
			"		STR	R9, [R2,#-4]                       \n"
			"		LDR	R9, [R11,#var_50]                  \n"
			"		LDR	R12, [R11,#var_84]                 \n"
			"		MOV	R7, #0x4600                        \n"
			"		STRH	R10, [R8,R9]                   \n"
			"		LDR	R10, [R11,#var_98]                 \n"
			"		MOV	LR, #0xFFFFBCFF                    \n"
			"		MOV	R0, #0x4700                        \n"
			"		ADD	R7, R7,	#0xBE                      \n"
			"		SUB	LR, LR,	#0x7F                      \n"
			"		ADD	R0, R0,	#0xF0                      \n"
			"		STRH	R10, [R12,#2]                  \n"
			"		STRH	R7, [R12,#4]                   \n"
			"		ADD	R3, R3,	#5                         \n"
			"		SUB	R1, R1,	#2                         \n"
			"		MOV	R9, R12                            \n"
			"		LDR	R7, [R11,#var_48]                  \n"
			"		MOV	R10, R12                           \n"
			"		STRH	LR, [R12,#6]                   \n"
			"		STRH	R0, [R12,#8]                   \n"
			"		SUB	R2, R2,	#4                         \n"
			"		B	loc_1188                           \n"
			"loc_13D0:				                       \n"
			"		ADD	R0, R6,	R0                         \n"
			"		LDRH	R0, [R0,#2]                    \n"
			"		AND	R1, R0,	#0xD000                    \n"
			"		CMP	R1, #0x9000                        \n"
			"		BEQ	loc_1408                           \n"
			"		CMP	R1, #0x8000                        \n"
			"		BEQ	loc_1AEC                           \n"
			"		CMP	R1, #0xD000                        \n"
			"		BEQ	loc_1408                           \n"
			"loc_13F4:				                       \n"
			"		MOV	R1, %[VAL_D001]                    \n"
			"		AND	R1, R0,	R1                         \n"
			"		CMP	R1, #0xC000                        \n"
			"		BNE	loc_E70                            \n"
			"loc_1408:				                       \n"
			"					                           \n"
			"		ADD	R3, R3,	#1                         \n"
			"		ADD	R3, R3,	#1                         \n"
			"		CMP	R3, R4                             \n"
			"		ADD	R12, R12, #0xA                     \n"
			"		BNE	loc_E3C                            \n"
			"		B	loc_EB4                            \n"
			"loc_1420:				                       \n"
			"		LDRH	R2, [R5]                       \n"
			"		MOV	R3, %[VAL_46C0]                    \n"
			"		CMP	R2, R3                             \n"
			"		BNE	loc_D68                            \n"
			"		LDR	R7, [R11,#var_70]                  \n"
			"		MOV	R3, %[VAL_4778]                    \n"
			"		LDRH	R2, [R5,R7]                    \n"
			"		CMP	R2, R3                             \n"
			"		BNE	loc_D68                            \n"
			"		B	loc_18BC                           \n"
			"loc_14A8:				                       \n"
			"		BL	__errno                            \n"
			"		LDR	R3, [R0]                           \n"
			"		CMP	R3, #4                             \n"
			"		BEQ	loc_EDC                            \n"
			"		BL	__errno                            \n"
			"		LDR	R12, [R11,#var_74]                 \n"
			"		STR	R7, [R12]                          \n"
			"		B	loc_10F4                           \n"
			"loc_14DC:				                       \n"
			"		AND	R0, LR,	#0x300                     \n"
			"		CMP	R0, #0x300                         \n"
			"		BEQ	loc_1298                           \n"
			"loc_14E8:				                       \n"
			"		ADD	R7, R7,	#1                         \n"
			"		MOV	R0, R7,LSL#1                       \n"
			"		LDRH	R0, [R6,R0]                    \n"
			"		AND	R10, LR, #0x3F                     \n"
			"		MOV	R10, R10,LSL#12                    \n"
			"		MOV	R9, R0,LSL#21                      \n"
			"		MOV	R0, R0,LSL#16                      \n"
			"		ORR	R10, R10, R9,LSR#20                \n"
			"		ORR	R10, R10, #1                       \n"
			"		TST	R0, #0x10000000                    \n"
			"		STR	R10, [R11,#var_48]                 \n"
			"		MOV	R10, LR,LSL#16                     \n"
			"		BNE	loc_15B8                           \n"
			"		MOV	R9, R0,LSR#8                       \n"
			"		STR	R9, [R11,#var_4C]                  \n"
			"		MOV	R9, R10,LSR#6                      \n"
			"		STR	R9, [R11,#var_50]                  \n"
			"		LDR	R9, [R11,#var_4C]                  \n"
			"		MOV	R0, R0,LSR#11                      \n"
			"		STR	R0, [R11,#var_84]                  \n"
			"		AND	R9, R9,	#0x80000                   \n"
			"		STR	R9, [R11,#var_4C]                  \n"
			"		LDR	R9, [R11,#var_50]                  \n"
			"		LDR	R0, [R11,#var_4C]                  \n"
			"		AND	LR, LR,	#0x3C0                     \n"
			"		AND	R9, R9,	#0x100000                  \n"
			"		ORR	R0, R0,	R9                         \n"
			"		STR	R9, [R11,#var_50]                  \n"
			"		LDR	R9, [R11,#var_84]                  \n"
			"		STR	R0, [R11,#var_4C]                  \n"
			"		CMP	LR, #0x380                         \n"
			"		AND	R0, R9,	#0x40000                   \n"
			"		LDR	R9, [R11,#var_4C]                  \n"
			"		ORR	R0, R9,	R0                         \n"
			"		LDR	R9, [R11,#var_48]                  \n"
			"		ORR	R0, R0,	R9                         \n"
			"		MOV	R0, R0,LSL#11                      \n"
			"		MOV	LR, R0,ASR#11                      \n"
			"		ADD	R0, R8,	R3,LSL#1                   \n"
			"		BEQ	loc_1610                           \n"
			"		SUB	R9, R1,	#0x80000008                \n"
			"		MOV	R10, R10,LSR#14                    \n"
			"		RSB	R9, R3,	R9                         \n"
			"		AND	R10, R10, #0xF00                   \n"
			"		AND	R9, R9,	#0xFF                      \n"
			"		ORR	R10, R10, #0xD000                  \n"
			"		ORR	R10, R10, R9                       \n"
			"loc_15A4:				                       \n"
			"		ADD	R12, R5, R12                       \n"
			"		ADD	R12, R12, #4                       \n"
			"		ADD	R12, R12, LR                       \n"
			"		STRH	R10, [R0]                      \n"
			"		B	loc_11F8                           \n"
			"loc_15B8:				                       \n"
			"		MOV	LR, R0,LSL#2                       \n"
			"		MOV	R0, R0,LSL#4                       \n"
			"		MOV	R9, R10,LSR#26                     \n"
			"		STR	R0, [R11,#var_4C]                  \n"
			"		MOV	R10, R10,LSR#4                     \n"
			"		LDR	R0, [R11,#var_48]                  \n"
			"		AND	R9, R9,	#1                         \n"
			"		AND	R10, R10, #0x3C0000                \n"
			"		ORR	R10, R10, R9,LSL#24                \n"
			"		ORR	R10, R10, R0                       \n"
			"		LDR	R0, [R11,#var_4C]                  \n"
			"		CMP	R9, LR,LSR#31                      \n"
			"		MOVNE	LR, #0                         \n"
			"		MOVEQ	LR, #0x800000                  \n"
			"		CMP	R9, R0,LSR#31                      \n"
			"		MOVNE	R0, #0                         \n"
			"		MOVEQ	R0, #0x400000                  \n"
			"		ORR	LR, R10, LR                        \n"
			"		ORR	LR, LR,	R0                         \n"
			"		MOV	LR, LR,LSL#7                       \n"
			"		ADD	R0, R8,	R3,LSL#1                   \n"
			"		MOV	LR, LR,ASR#7                       \n"
			"loc_1610:				                       \n"
			"		SUB	R10, R1, #0x80000008               \n"
			"		RSB	R10, R3, R10                       \n"
			"		MOV	R10, R10,LSL#21                    \n"
			"		MOV	R10, R10,LSR#21                    \n"
			"		ORR	R10, R10, #0xE000                  \n"
			"		B	loc_15A4                           \n"
			"loc_1628:				                       \n"
			"		SUB	R9, R1,	#0x8000000F                \n"
			"		MOV	R10, LR,LSL#16                     \n"
			"		RSB	R9, R3,	R9                         \n"
			"		AND	LR, LR,	#7                         \n"
			"		STR	LR, [R11,#var_48]                  \n"
			"		MOV	R9, R9,LSL#1                       \n"
			"		STR	R9, [R11,#var_84]                  \n"
			"		LDR	R9, [R11,#var_48]                  \n"
			"		MOV	R0, R10,LSR#16                     \n"
			"		MOV	LR, R10,LSR#19                     \n"
			"		AND	R0, R0,	#0x800                     \n"
			"		ORR	R0, R0,	R9                         \n"
			"		AND	R9, LR,	#0x40                      \n"
			"		LDR	LR, [R11,#var_84]                  \n"
			"		MOV	R10, R10,LSR#18                    \n"
			"		AND	R10, R10, #0x3E                    \n"
			"		AND	LR, LR,	#0x40                      \n"
			"		ORR	R10, R9, R10                       \n"
			"		MOV	R9, LR,LSR#6                       \n"
			"		STR	R9, [R11,#var_50]                  \n"
			"		LDR	R9, [R11,#var_48]                  \n"
			"		ORR	R0, R0,	#0xFF000000                \n"
			"		ORR	R0, R0,	#0xFF0000                  \n"
			"		CMP	R9, #7                             \n"
			"		LDR	R9, [R11,#var_50]                  \n"
			"		ORR	R0, R0,	#0xB100                    \n"
			"		ORR	R10, R10, #1                       \n"
			"		ORR	R0, R0,	R9,LSL#9                   \n"
			"		STR	R10, [R11,#var_4C]                 \n"
			"		STR	R0, [R11,#var_94]                  \n"
			"		LDR	R0, [R11,#var_84]                  \n"
			"		LDR	R9, [R11,#var_4C]                  \n"
			"		ADD	R12, R5, R12                       \n"
			"		AND	R0, R0,	#0x3E                      \n"
			"		STR	R0, [R11,#var_98]                  \n"
			"		ADD	R9, R9,	#4                         \n"
			"		ADD	R0, R8,	R3,LSL#1                   \n"
			"		STR	R9, [R11,#var_A8]                  \n"
			"		STR	R0, [R11,#var_88]                  \n"
			"		STR	R0, [R11,#var_8C]                  \n"
			"		STR	R0, [R11,#var_90]                  \n"
			"		STR	R0, [R11,#var_9C]                  \n"
			"		STR	R0, [R11,#var_A0]                  \n"
			"		STR	R0, [R11,#var_A4]                  \n"
			"		LDR	R9, =0x8C00F387                    \n"
			"		LDR	R0, =0x8C00F386                    \n"
			"		STR	R12, [R11,#var_50]                 \n"
			"		MOV	R12, R3,LSL#1                      \n"
			"		MOVNE	R0, R9                         \n"
			"		STR	R12, [R11,#var_84]                 \n"
			"		LDR	R12, [R11,#var_38]                 \n"
			"		STR	R0, [R2,#-0x14]                    \n"
			"		MOV	R10, #0xBC00                       \n"
			"		LDR	R0, =0x46C0BC40                    \n"
			"		LDR	R9, =0x46C0BC80                    \n"
			"		ADD	R10, R10, #0x40                    \n"
			"		MOVEQ	R12, R10                       \n"
			"		LDR	R10, [R11,#var_3C]                 \n"
			"		MOVEQ	R9, R0                         \n"
			"		MOV	LR, #0xB400                        \n"
			"		STR	R9, [R2,#-0x10]                    \n"
			"		LDR	R0, [R11,#var_40]                  \n"
			"		LDR	R9, [R11,#var_44]                  \n"
			"		ADD	LR, LR,	#0x40                      \n"
			"		MOVNE	LR, R10                        \n"
			"		STR	R12, [R11,#var_48]                 \n"
			"		LDR	R10, [R11,#var_98]                 \n"
			"		LDR	R12, [R11,#var_94]                 \n"
			"		MOVEQ	R0, R9                         \n"
			"		STR	R0, [R11,#var_4C]                  \n"
			"		ORR	R0, R12, R10,LSL#2                 \n"
			"		LDR	R10, [R11,#var_50]                 \n"
			"		LDR	R12, [R11,#var_A8]                 \n"
			"		MOVNE	R9, #0x8700                    \n"
			"		MOVEQ	R9, #0x8600                    \n"
			"		ADD	R3, R3,	#7                         \n"
			"		ADD	R12, R12, R10                      \n"
			"		STR	R12, [R2,#-4]                      \n"
			"		LDR	R10, [R11,#var_88]                 \n"
			"		LDR	R12, [R11,#var_84]                 \n"
			"		SUB	R1, R1,	#0xA                       \n"
			"		STRH	LR, [R8,R12]                   \n"
			"		STRH	R0, [R10,#6]                   \n"
			"		LDR	R0, [R11,#var_4C]                  \n"
			"		LDR	R12, [R11,#var_48]                 \n"
			"		MOV	LR, #0xFFFFF3EF                    \n"
			"		STRH	R0, [R10,#8]                   \n"
			"		MOV	R0, #0x8C00                        \n"
			"		STRH	R0, [R10,#0xA]                 \n"
			"		LDR	R0, =0xE51FF004                    \n"
			"		STRH	R9, [R10,#4]                   \n"
			"		STRH	LR, [R10,#2]                   \n"
			"		STRH	R12, [R10,#0xC]                \n"
			"		STR	R0, [R2,#-8]                       \n"
			"		LDR	R0, =0x46C04778                    \n"
			"		MOV	R9, R10                            \n"
			"		STR	R0, [R2,#-0xC]                     \n"
			"		SUB	R2, R2,	#0x14                      \n"
			"		B	loc_1188                           \n"
			"loc_17E4:				                       \n"
			"		ADD	R7, R7,	#1                         \n"
			"		MOV	R0, R7,LSL#1                       \n"
			"		LDRH	R0, [R6,R0]                    \n"
			"		STR	R7, [R11,#var_48]                  \n"
			"		SUB	R9, R1,	#0x80000004                \n"
			"		STR	R0, [R11,#var_4C]                  \n"
			"		LDR	R7, [R11,#var_4C]                  \n"
			"		ANDS	R0, R3,	#1                     \n"
			"		MOVNE	R0, #2                         \n"
			"		RSB	R9, R3,	R9                         \n"
			"		MOV	R10, R7,LSR#12                     \n"
			"		ADD	R9, R0,	R9,LSL#1                   \n"
			"		ADD	R12, R5, R12                       \n"
			"		MOV	R0, #0x8D000000                    \n"
			"		STR	R12, [R11,#var_90]                 \n"
			"		MOV	R0, R0,ASR#20                      \n"
			"		ORR	R0, R10, R0                        \n"
			"		MOV	R7, R10,LSL#12                     \n"
			"		LDR	R10, [R11,#var_90]                 \n"
			"		MOV	R12, R3,LSL#1                      \n"
			"		STR	R12, [R11,#var_50]                 \n"
			"		ADD	R12, R8, R3,LSL#1                  \n"
			"		STR	R12, [R11,#var_84]                 \n"
			"		STR	R12, [R11,#var_88]                 \n"
			"		STR	R12, [R11,#var_8C]                 \n"
			"		ADD	R12, R10, #4                       \n"
			"		LDR	R10, [R11,#var_50]                 \n"
			"		CMP	R9, #0                             \n"
			"		RSBLT	R9, R9,	#0                     \n"
			"		TST	LR, #0x80                          \n"
			"		MOV	LR, #0xFFFFF8DF                    \n"
			"		STRH	LR, [R8,R10]                   \n"
			"		LDR	R10, [R11,#var_84]                 \n"
			"		ORR	R9, R9,	R7                         \n"
			"		BIC	R12, R12, #2                       \n"
			"		STRH	R7, [R10,#6]                   \n"
			"		LDREQ	R7, [R11,#var_4C]              \n"
			"		STRH	R9, [R10,#2]                   \n"
			"		MOV	R9, R10                            \n"
			"		LDRNE	R9, [R11,#var_4C]              \n"
			"		STRH	R0, [R10,#4]                   \n"
			"		MOVEQ	R0, R7,LSL#20                  \n"
			"		MOVNE	R0, R9,LSL#20                  \n"
			"		MOVEQ	R0, R0,LSR#20                  \n"
			"		RSBEQ	R0, R0,	#0                     \n"
			"		MOVNE	R0, R0,LSR#20                  \n"
			"		SUB	LR, R2,	#4                         \n"
			"		ADD	R0, R0,	R12                        \n"
			"		STR	R0, [R2,#-4]                       \n"
			"		ADD	R3, R3,	#4                         \n"
			"		SUB	R1, R1,	#2                         \n"
			"		LDR	R7, [R11,#var_48]                  \n"
			"		MOV	R2, LR                             \n"
			"		B	loc_1188                           \n"
			"loc_18BC:				                       \n"
			"					                           \n"
			"		LDR	R9, [R11,#var_64]                  \n"
			"		MOV	R3, %[VAL_46C0]                    \n"
			"		LDRH	R2, [R9,#2]                    \n"
			"		CMP	R2, R3                             \n"
			"		BNE	loc_D68                            \n"
			"		LDR	R12, [R11,#var_64]                 \n"
			"		LDR	R3, =0xE51FF004                    \n"
			"		LDR	R2, [R12,#4]                       \n"
			"		CMP	R2, R3                             \n"
			"		BNE	loc_D68                            \n"
			"		LDR	R7, [R11,#var_74]                  \n"
			"		CMP	R7, #0                             \n"
			"		LDRNE	R3, [R12,#8]                   \n"
			"		STRNE	R3, [R7]                       \n"
			"loc_1910:				                       \n"
			"		LDR	R10, [R11,#var_64]                 \n"
			"		MOV	R0, #0                             \n"
			"		MOV	R1, R0                             \n"
			"		ADD	R2, R10, #8                        \n"
			"		MOV	R3, #4                             \n"
			"		BL	ModForRWEAlloc                     \n"
			"		LDR	R12, [R11,#var_80]                 \n"
			"		CMP	R0, #0                             \n"
			"		STR	R12, [R10,#8]                      \n"
			"		BEQ	loc_193C                           \n"
			"		BL	ModForRWEFree                      \n"
			"loc_193C:				                       \n"
			"		BEQ	loc_10F4                           \n"
			"loc_1978:				                       \n"
			"		TST	LR, #0x80                          \n"
			"		STRH	LR, [R11,#var_48]              \n"
			"		BNE	loc_1B40                           \n"
			"		AND	R9, LR,	#7                         \n"
			"		CMP	R9, #7                             \n"
			"		LDR	R9, [R11,#var_38]                  \n"
			"		MOV	R10, %[VAL_BC40]                   \n"
			"		MOVEQ	R9, R10                        \n"
			"		MOVNE	R10, #0x38                     \n"
			"		MOVEQ	R10, #0x30                     \n"
			"		STR	R10, [R11,#var_84]                 \n"
			"		LDR	R10, [R11,#var_3C]                 \n"
			"		MOV	R0, %[VAL_B440]                    \n"
			"		MOVEQ	R10, R0                        \n"
			"		LDRH	R0, [R11,#var_48]              \n"
			"		STR	R10, [R11,#var_4C]                 \n"
			"		STR	R9, [R11,#var_88]                  \n"
			"		AND	R0, R0,	#7                         \n"
			"		STR	R0, [R11,#var_90]                  \n"
			"		LDR	R10, [R11,#var_90]                 \n"
			"		MOVNE	R9, #7                         \n"
			"		MOVEQ	R9, #6                         \n"
			"		ANDS	R0, R3,	#1                     \n"
			"		MOVNE	R0, #2                         \n"
			"		MOV	LR, LR,LSR#4                       \n"
			"		STR	R0, [R11,#var_48]                  \n"
			"		AND	LR, LR,	#8                         \n"
			"		ORR	LR, LR,	R10                        \n"
			"		LDR	R10, [R11,#var_48]                 \n"
			"		STR	R9, [R11,#var_50]                  \n"
			"		SUB	R9, R1,	#0x80000006                \n"
			"		RSB	R9, R3,	R9                         \n"
			"		ADD	R9, R10, R9,LSL#1                  \n"
			"		LDR	R10, [R11,#var_90]                 \n"
			"		STR	R9, [R11,#var_48]                  \n"
			"		MOV	R0, LR,LSR#3                       \n"
			"		MOV	R10, R10,LSL#8                     \n"
			"		STR	R10, [R11,#var_8C]                 \n"
			"		LDR	R10, [R11,#var_48]                 \n"
			"		AND	LR, LR,	#7                         \n"
			"		MOV	R9, LR,LSL#3                       \n"
			"		MOV	R10, R10,LSL#22                    \n"
			"		STR	R10, [R11,#var_90]                 \n"
			"		LDR	R10, [R11,#var_8C]                 \n"
			"		ADD	R12, R5, R12                       \n"
			"		ORR	LR, LR,	#0x4400                    \n"
			"		ORR	R10, R10, #0x4800                  \n"
			"		STR	R10, [R11,#var_A0]                 \n"
			"		STR	R12, [R11,#var_A4]                 \n"
			"		ORR	R9, R9,	R0,LSL#6                   \n"
			"		MOV	R12, R3,LSL#1                      \n"
			"		ORR	LR, LR,	R0,LSL#7                   \n"
			"		ADD	R0, R8,	R3,LSL#1                   \n"
			"		STR	R12, [R11,#var_9C]                 \n"
			"		STR	R0, [R11,#var_48]                  \n"
			"		LDR	R10, [R11,#var_50]                 \n"
			"		LDR	R12, [R11,#var_A0]                 \n"
			"		STR	R0, [R11,#var_8C]                  \n"
			"		STR	R0, [R11,#var_94]                  \n"
			"		STR	R0, [R11,#var_98]                  \n"
			"		LDR	R0, [R11,#var_90]                  \n"
			"		ORR	R9, R9,	#0x4600                    \n"
			"		ORR	R9, R10, R9                        \n"
			"		ORR	R10, R12, R0,LSR#24                \n"
			"		LDR	R0, [R11,#var_A4]                  \n"
			"		LDR	R12, [R11,#var_84]                 \n"
			"		ADD	R3, R3,	#5                         \n"
			"		ADD	R0, R0,	#4                         \n"
			"		STR	R0, [R2,#-4]                       \n"
			"		ORR	LR, R12, LR                        \n"
			"		LDR	R0, [R11,#var_4C]                  \n"
			"		LDR	R12, [R11,#var_9C]                 \n"
			"		SUB	R1, R1,	#2                         \n"
			"		SUB	R2, R2,	#4                         \n"
			"		STRH	R0, [R8,R12]                   \n"
			"		LDR	R12, [R11,#var_48]                 \n"
			"		STRH	R9, [R12,#2]                   \n"
			"		STRH	R10, [R12,#4]                  \n"
			"		LDR	R10, [R11,#var_88]                 \n"
			"		MOV	R9, R12                            \n"
			"		STRH	LR, [R12,#6]                   \n"
			"		STRH	R10, [R12,#8]                  \n"
			"		B	loc_1188                           \n"
			"loc_1ACC:				                       \n"
			"		TST	R2, #0x1800                        \n"
			"		ADDNE	R3, R3,	#1                     \n"
			"		B	loc_EA8                            \n"
			"loc_1AD8:				                       \n"
			"		ADD	R3, R3,	#1                         \n"
			"		CMP	R3, R4                             \n"
			"		ADD	R12, R12, #0x20                    \n"
			"		BNE	loc_E3C                            \n"
			"		B	loc_EB4                            \n"
			"loc_1AEC:				                       \n"
			"		AND	R1, R2,	#0x300                     \n"
			"		CMP	R1, #0x300                         \n"
			"		BNE	loc_1408                           \n"
			"		B	loc_13F4                           \n"
			"loc_1AFC:				                       \n"
			"		TST	LR, #0x1800                        \n"
			"		BEQ	loc_FC8                            \n"
			"		ADD	R7, R7,	#1                         \n"
			"		STRH	LR, [R8,R0]                    \n"
			"		MOV	R0, R7,LSL#1                       \n"
			"		LDRH	R12, [R6,R0]                   \n"
			"		ADD	R0, R8,	R3,LSL#1                   \n"
			"		ADD	R3, R3,	#2                         \n"
			"		STRH	R12, [R0,#2]                   \n"
			"		B	loc_1188                           \n"
			"loc_1B24:				                       \n"
			"		BL	__errno                            \n"
			"		B	loc_10F4                           \n"
			"loc_1B40:				                       \n"
			"		LDR	R4, [R11,#len]                     \n"
			"loc_1B58:				                       \n"
			"		MOV	R1, R4		                       \n"
			"		MOV	R0, R8		                       \n"
			"		BL	munmap                             \n"
			"		CMN	R0, #1                             \n"
			"		BEQ	loc_1B7C                           \n"
			"loc_1B6C:				                       \n"
			"		LDR	R9, [R11,#var_74]                  \n"
			"		MOV	R3, #0                             \n"
			"		STR	R3, [R9]                           \n"
			"		B	loc_10F4                           \n"
			"loc_1B7C:				                       \n"
			"		BL	__errno                            \n"
			"		LDR	R3, [R0]                           \n"
			"		CMP	R3, #4                             \n"
			"		BNE	loc_1B6C                           \n"
			"		B	loc_1B58                           \n"
			:
			:[VAL_4778]"r"(0x4778),[VAL_46C0]"r"(0x46C0),[VAL_D001]"r"(0xD001),[VAL_FFFFB480]"r"(0xFFFFB480),
			 [VAL_BC40]"r"(0xBC40),[VAL_B440]"r"(0xB440)
	);
}

extern "C" void HookFunctionInner(void *symbol, void *replace, void **result)
{
	asm(
			"fd		= -0x60                               \n"
			"offset		= -0x5C                           \n"
			"var_54		= -0x54                           \n"
			"replace_	= -0x50                           \n"
			"var_4C		= -0x4C                           \n"
			"var_48		= -0x48                           \n"
			"var_44		= -0x44                           \n"
			"firstdw_	= -0x40                           \n"
			"seconddw_	= -0x3C                           \n"
			"s		= -0x38                               \n"
			"		STMFD	SP!, {R4-R11,LR}              \n"
			"		SUB	SP, SP,	#0x3C                     \n"
			"		MOV	R4, R0                            \n"
			"		STR	R1, [SP,#0x60+replace_]           \n"
			"		MOV	R9, R2                            \n"
			"loc_1C5C:				                      \n"
			"		TST	R4, #1                            \n"
			"		BEQ	loc_1C7C                          \n"
			"		BIC	R0, R4,	#1                        \n"
			"		LDR	R1, [SP,#0x60+replace_]	          \n"
			"		MOV	R2, R9		                      \n"
			"		BL	HookFunctionThumb                 \n"
			"loc_1C74:				                      \n"
			"		ADD	SP, SP,	#0x3C                     \n"
			"		LDMFD	SP!, {R4-R11,PC}              \n"
			"loc_1C7C:				                      \n"
			"		CMP	R4, #0                            \n"
			"		BEQ	loc_1C74                          \n"
			"		LDR	R8, [R4]                          \n"
			"		LDR	R5, [R4,#4]                       \n"
			"		STR	R8, [SP,#0x60+firstdw_]           \n"
			"		STR	R5, [SP,#0x60+seconddw_]          \n"
			"loc_1CA0:				                      \n"
			"		CMP	R9, #0                            \n"
			"		BEQ	loc_1DB4                          \n"
			"		LDR	R3, =0xE51FF004                   \n"
			"		CMP	R8, R3                            \n"
			"		STREQ	R5, [R9]                      \n"
			"		BEQ	loc_1DB4                          \n"
			"		AND	R11, R8, #0xC000000               \n"
			"		CMP	R11, #0x4000000                   \n"
			"		STR	R11, [SP,#0x60+var_4C]            \n"
			"		BEQ	loc_1F54                          \n"
			"loc_1CC8:				                      \n"
			"		MOV	R7, #8                            \n"
			"loc_1CCC:				                      \n"
			"		LDR	R3, [SP,#0x60+seconddw_]          \n"
			"		AND	R2, R3,	#0xC000000                \n"
			"		CMP	R2, #0x4000000                    \n"
			"		BEQ	loc_1F2C                          \n"
			"loc_1CDC:				                      \n"
			"		ADD	R7, R7,	#8                        \n"
			"		MOV	R11, #0xFFFFFFFF                  \n"
			"		MOV	R10, #0                           \n"
			"loc_1CE8:				                      \n"
			"		MOV	R5, #0                            \n"
			"		MOV	R1, R7		                      \n"
			"		MOV	R2, #3		                      \n"
			"		MOV	R3, #0x22	                      \n"
			"		MOV	R0, R5		                      \n"
			"		STR	R11, [SP,#0x60+fd]                \n"
			"		STR	R10, [SP,#0x60+offset]            \n"
			"		BL	mmap                              \n"
			"		CMN	R0, #1                            \n"
			"		BEQ	loc_1F7C                          \n"
			"		LDR	R11, [SP,#0x60+var_4C]            \n"
			"		MOV	R2, R7,LSR#2                      \n"
			"		ADD	R3, R4,	#8                        \n"
			"		CMP	R11, #0x4000000                   \n"
			"		MOV	R10, R0                           \n"
			"		ADD	R12, R0, R2,LSL#2                 \n"
			"		MOV	R1, R3                            \n"
			"		ADD	R0, SP,	#0x60+firstdw_            \n"
			"		ADD	LR, SP,	#0x60+seconddw_           \n"
			"		STR	R3, [SP,#0x60+var_54]             \n"
			"		BEQ	loc_1E5C                          \n"
			"loc_1D3C:				                      \n"
			"		STR	R8, [R10,R5,LSL#2]                \n"
			"		ADD	R5, R5,	#1                        \n"
			"loc_1D44:				                      \n"
			"		CMP	R0, LR                            \n"
			"		ADD	R1, R1,	#4                        \n"
			"		BNE	loc_1E44                          \n"
			"		LDR	R3, [SP,#0x60+var_54]             \n"
			"		LDR	R1, =0xE51FF004                   \n"
			"		ADD	R2, R5,	#1                        \n"
			"		MOV	R0, R10		                      \n"
			"		STR	R1, [R10,R5,LSL#2]                \n"
			"		STR	R3, [R10,R2,LSL#2]                \n"
			"		MOV	R1, R7		                      \n"
			"		MOV	R2, #5		                      \n"
			"		BL	mprotect                          \n"
			"		CMN	R0, #1                            \n"
			"		BEQ	loc_1FD8                          \n"
			"		STR	R10, [R9]                         \n"
			"loc_1DB4:				                      \n"
			"		MOV	R0, #0                            \n"
			"		MOV	R3, #8                            \n"
			"		MOV	R1, R0                            \n"
			"		MOV	R2, R4                            \n"
			"		BL	ModForRWEAlloc                    \n"
			"		LDR	R5, [SP,#0x60+replace_]           \n"
			"		LDR	R3, =0xE51FF004                   \n"
			"		CMP	R0, #0                            \n"
			"		STR	R5, [R4,#4]                       \n"
			"		STR	R3, [R4]                          \n"
			"		BEQ	loc_1DE4                          \n"
			"		BL	ModForRWEFree                     \n"
			"loc_1DE4:				                      \n"
			"		B	loc_1C74                          \n"
			"loc_1E44:				                      \n"
			"		LDR	R8, [R0,#4]!                      \n"
			"		AND	R11, R8, #0xC000000               \n"
			"		STR	R11, [SP,#0x60+var_4C]            \n"
			"		LDR	R11, [SP,#0x60+var_4C]            \n"
			"		CMP	R11, #0x4000000                   \n"
			"		BNE	loc_1D3C                          \n"
			"loc_1E5C:				                      \n"
			"		AND	R11, R8, #0xF0000000              \n"
			"		CMP	R11, #0xF0000000                  \n"
			"		BEQ	loc_1D3C                          \n"
			"		AND	R11, R8, #0xF0000                 \n"
			"		CMP	R11, #0xF0000                     \n"
			"		BNE	loc_1D3C                          \n"
			"		MOV	R11, R8,LSR#12                    \n"
			"		TST	R8, #0x2000000                    \n"
			"		ANDEQ	R11, R11, #0xF                \n"
			"		BEQ	loc_1E98                          \n"
			"		AND	R3, R11, #0xF                     \n"
			"		AND	R11, R8, #0xF                     \n"
			"		CMP	R3, R11                           \n"
			"		MOV	R11, R3                           \n"
			"		BEQ	loc_2010                          \n"
			"loc_1E98:				                      \n"
			"		BIC	R8, R8,	#0xF0000                  \n"
			"		ORR	R8, R8,	R11,LSL#16                \n"
			"		MOV	R3, #0                            \n"
			"		STR	R8, [SP,#0x60+var_44]             \n"
			"		STR	R11, [SP,#0x60+var_4C]            \n"
			"		MOV	R8, R5                            \n"
			"		STR	R3, [SP,#0x60+var_48]             \n"
			"loc_1EB4:				                      \n"
			"		LDR	R3, [SP,#0x60+var_4C]             \n"
			"		SUB	R11, R2, #0xC0000003              \n"
			"		RSB	R11, R8, R11                      \n"
			"		MOV	R5, R3,LSL#12                     \n"
			"		LDR	R3, [SP,#0x60+var_48]             \n"
			"		MOV	R11, R11,LSL#2                    \n"
			"		ORR	R5, R5,	#0xE5000000               \n"
			"		CMP	R11, #0                           \n"
			"		RSBLT	R11, R11, #0                  \n"
			"		CMP	R3, #0                            \n"
			"		LDR	R3, [SP,#0x60+var_44]             \n"
			"		ORR	R5, R5,	#0x9F0000                 \n"
			"		ORR	R5, R5,	R11                       \n"
			"		ADD	R11, R8, #1                       \n"
			"		STR	R5, [R10,R8,LSL#2]                \n"
			"		ADD	R5, R8,	#2                        \n"
			"		STR	R3, [R10,R11,LSL#2]               \n"
			"		BEQ	loc_1F1C                          \n"
			"		LDR	R3, [SP,#0x60+var_4C]             \n"
			"		MOV	R11, #1                           \n"
			"		MOV	R11, R11,LSL R3                   \n"
			"		STR	R11, [SP,#0x60+var_4C]            \n"
			"		ORR	R11, R11, #0xE8000000             \n"
			"		ORR	R11, R11, #0xBD0000               \n"
			"		STR	R11, [R10,R5,LSL#2]               \n"
			"		ADD	R5, R8,	#3                        \n"
			"loc_1F1C:				                      \n"
			"		STR	R1, [R12,#-4]                     \n"
			"		SUB	R2, R2,	#1                        \n"
			"		SUB	R12, R12, #4                      \n"
			"		B	loc_1D44                          \n"
			"loc_1F2C:				                      \n"
			"		AND	R2, R3,	#0xF0000000               \n"
			"		CMP	R2, #0xF0000000                   \n"
			"		BEQ	loc_1CDC                          \n"
			"		AND	R2, R3,	#0xF0000                  \n"
			"		CMP	R2, #0xF0000                      \n"
			"		BNE	loc_1CDC                          \n"
			"		TST	R3, #0x2000000                    \n"
			"		ADDEQ	R7, R7,	#8                    \n"
			"		ADDNE	R7, R7,	#0x10                 \n"
			"		B	loc_1CDC                          \n"
			"loc_1F54:				                      \n"
			"		AND	R3, R8,	#0xF0000000               \n"
			"		CMP	R3, #0xF0000000                   \n"
			"		BEQ	loc_1CC8                          \n"
			"		AND	R3, R8,	#0xF0000                  \n"
			"		CMP	R3, #0xF0000                      \n"
			"		BNE	loc_1CC8                          \n"
			"		TST	R8, #0x2000000                    \n"
			"		MOVNE	R7, #0x18                     \n"
			"		MOVEQ	R7, #0x10                     \n"
			"		B	loc_1CCC                          \n"
			"loc_1F7C:				                      \n"
			"		BL	__errno                           \n"
			"		LDR	R3, [R0]                          \n"
			"		CMP	R3, #4                            \n"
			"		BEQ	loc_1CE8                          \n"
			"		BL	__errno                           \n"
			"		STR	R5, [R9]                          \n"
			"		B	loc_1C74                          \n"
			"loc_1FD8:				                      \n"
			"		BL	__errno                           \n"
			"loc_1FF0:				                      \n"
			"		MOV	R1, R7		                      \n"
			"		MOV	R0, R10		                      \n"
			"		BL	munmap                            \n"
			"		CMN	R0, #1                            \n"
			"		BEQ	loc_204C                          \n"
			"loc_2004:				                      \n"
			"		MOV	R3, #0                            \n"
			"		STR	R3, [R9]                          \n"
			"		B	loc_1C74                          \n"
			"loc_2010:				                      \n"
			"		RSBS	R3, R3,	#1                    \n"
			"		MOVCC	R3, #0                        \n"
			"		MOV	R11, #1                           \n"
			"		MOV	R11, R11,LSL R3                   \n"
			"		BIC	R8, R8,	#0xF0000                  \n"
			"		ORR	R11, R11, #0xE9000000             \n"
			"		ORR	R8, R8,	R3,LSL#16                 \n"
			"		STR	R3, [SP,#0x60+var_4C]             \n"
			"		ORR	R11, R11, #0x2D0000               \n"
			"		MOV	R3, #1                            \n"
			"		STR	R8, [SP,#0x60+var_44]             \n"
			"		STR	R11, [R10,R5,LSL#2]               \n"
			"		ADD	R8, R5,	#1                        \n"
			"		STR	R3, [SP,#0x60+var_48]             \n"
			"		B	loc_1EB4                          \n"
			"loc_204C:				                      \n"
			"		BL	__errno                           \n"
			"		LDR	R3, [R0]                          \n"
			"		CMP	R3, #4                            \n"
			"		BNE	loc_2004                          \n"
			"		B	loc_1FF0                          \n"
	);
}

JNIEXPORT void JNICALL MSHookFunction(void *symbol, void *replace, void **result)
{
	if(MSDebug)
		LOGI("SubstrateHookFunction(%p, %p, %p, %p)", 0, symbol, replace, result);
	if(!symbol || !replace)
		return;
	MSHookFunctionInner(symbol, replace, result);
}

